document.addEventListener("DOMContentLoaded", function () {

  // ===== ELEMENT REFERENCES =====
  const modal = document.getElementById("loginModal");
  const loginForm = document.getElementById("loginForm");
  const attendanceSection = document.getElementById("attendancePage");
  const uploadSection = document.getElementById("uploadPage");
  const notesSection = document.getElementById("notesPage");
  const skillsSection = document.getElementById("homePage");
  const heroSection = document.querySelector(".hero-banner");
  const qrContainer = document.getElementById("qrCode");
  const listContainer = document.getElementById("attendanceList");
  const studentCountEl = document.getElementById("studentCount");

  // Nav links (by ID for reliability)
  const homeNavLink = document.getElementById("homeNavLink");
  const attendanceNavLink = document.getElementById("attendanceNavLink");
  const uploadNavLink = document.getElementById("uploadNavLink");
  const notesNavLink = document.getElementById("notesNavLink");
  const loginNavLink = document.getElementById("loginNavLink");
  const darkModeToggle = document.getElementById("darkModeToggle");

  // Hamburger
  const hamburger = document.getElementById("hamburger");
  const mainNav = document.getElementById("mainNav");
  const navOverlay = document.getElementById("navOverlay");

  // ===== STATE =====
  let isLoggedIn = false;
  let attendanceActive = false;
  let currentQRCode = null;
  let usedCodes = new Set();
  let attendanceList = JSON.parse(localStorage.getItem("attendanceList")) || [];
  let uploadedNotes = JSON.parse(localStorage.getItem("uploadedNotes")) || [];

  // ===== TOAST HELPER =====
  function showToast(msg) {
    const toast = document.getElementById("toast");
    toast.textContent = msg;
    toast.classList.add("show");
    setTimeout(() => toast.classList.remove("show"), 3000);
  }

  // ===== FAKE DOWNLOAD HELPER =====
  // Triggers a real browser download of a placeholder text file,
  // since this demo doesn't have a backend file store.
  function triggerDownload(title) {
    const content =
      `${title}\n\nThis is a placeholder file generated by the Assignments & Notes Hub demo.\n` +
      `In a production version, this would download the real uploaded document.`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/[^a-z0-9]+/gi, "_")}.txt`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  // ===== RENDER UPLOADED NOTES INTO NOTES LIBRARY =====
  function renderUploadedNotes() {
    // Remove any previously-rendered dynamic items first
    document.querySelectorAll(".notes-list .dynamic-note").forEach(el => el.remove());

    uploadedNotes.forEach(note => {
      const list = document.getElementById(`notes-${note.subject}`);
      if (!list) return;

      const li = document.createElement("li");
      li.className = "dynamic-note";

      const span = document.createElement("span");
      span.textContent = note.title;

      const btn = document.createElement("button");
      btn.className = "download-note-btn";
      btn.textContent = "Download";
      btn.addEventListener("click", () => {
        triggerDownload(note.title);
        showToast(`📥 Downloading: ${note.title}`);
      });

      li.appendChild(span);
      li.appendChild(btn);
      list.appendChild(li);
    });
  }

  // ===== PAGE SWITCHER =====
  function showPage(page) {
    // Hide all pages
    heroSection.style.display = "none";
    skillsSection.style.display = "none";
    attendanceSection.style.display = "none";
    uploadSection.style.display = "none";
    notesSection.style.display = "none";

    // Show requested page
    if (page === "home") {
      heroSection.style.display = "block";
      skillsSection.style.display = "block";
    } else if (page === "attendance") {
      attendanceSection.style.display = "flex";
    } else if (page === "upload") {
      uploadSection.style.display = "flex";
    } else if (page === "notes") {
      notesSection.style.display = "block";
    }

    window.scrollTo({ top: 0, behavior: "smooth" });
    closeNav(); // always close mobile nav after navigating
  }

  // ===== HAMBURGER / MOBILE NAV =====
  function openNav() {
    hamburger.classList.add("open");
    hamburger.setAttribute("aria-expanded", "true");
    mainNav.classList.add("open");
    navOverlay.classList.add("active");
    document.body.style.overflow = "hidden";
  }

  function closeNav() {
    hamburger.classList.remove("open");
    hamburger.setAttribute("aria-expanded", "false");
    mainNav.classList.remove("open");
    navOverlay.classList.remove("active");
    document.body.style.overflow = "";
  }

  hamburger.addEventListener("click", () => {
    if (mainNav.classList.contains("open")) {
      closeNav();
    } else {
      openNav();
    }
  });

  navOverlay.addEventListener("click", closeNav);

  // Close nav on ESC
  document.addEventListener("keydown", (e) => {
    if (e.key === "Escape") {
      closeNav();
      modal.style.display = "none";
      document.querySelectorAll(".custom-alert-overlay").forEach(el => el.style.display = "none");
    }
  });

  // ===== DARK MODE =====
  if (localStorage.getItem("darkMode") === "enabled") {
    document.body.classList.add("dark-mode");
    updateDarkModeIcon();
  }

  darkModeToggle.addEventListener("click", () => {
    document.body.classList.toggle("dark-mode");
    localStorage.setItem("darkMode", document.body.classList.contains("dark-mode") ? "enabled" : "disabled");
    updateDarkModeIcon();
  });

  function updateDarkModeIcon() {
    const icon = darkModeToggle.querySelector("i");
    if (document.body.classList.contains("dark-mode")) {
      icon.className = "fas fa-sun";
    } else {
      icon.className = "fas fa-moon";
    }
  }

  // ===== HOME NAV =====
  homeNavLink.addEventListener("click", (e) => {
    e.preventDefault();
    showPage("home");
  });

  // ===== LOGIN / LOGOUT =====
  loginNavLink.addEventListener("click", (e) => {
    e.preventDefault();
    closeNav();
    if (!isLoggedIn) {
      modal.style.display = "flex";
    } else {
      isLoggedIn = false;
      loginNavLink.textContent = "Login";
      showPage("home");
      showToast("You have been logged out!");
    }
  });

  // Close modal when clicking backdrop
  modal.addEventListener("click", (e) => {
    if (e.target === modal) modal.style.display = "none";
  });

  // Login form submit
  loginForm.addEventListener("submit", (e) => {
    e.preventDefault();
    const username = document.getElementById("username").value.trim();
    if (!username) return;

    modal.style.display = "none";
    isLoggedIn = true;
    loginNavLink.textContent = "Logout";
    loginForm.reset();

    showToast(`Welcome, ${username}! Login successful 🎉`);
  });

  // ===== ATTENDANCE NAV =====
  attendanceNavLink.addEventListener("click", (e) => {
    e.preventDefault();
    if (!isLoggedIn) {
      closeNav();
      document.getElementById("customAlert").style.display = "flex";
      return;
    }
    showPage("attendance");
    if (attendanceActive) generateQRCode();
  });

  // ===== UPLOAD NAV =====
  uploadNavLink.addEventListener("click", (e) => {
    e.preventDefault();
    if (!isLoggedIn) {
      closeNav();
      document.getElementById("uploadAlert").style.display = "flex";
      return;
    }
    showPage("upload");
  });

  // ===== NOTES NAV =====
  notesNavLink.addEventListener("click", (e) => {
    e.preventDefault();
    showPage("notes");
  });

  // ===== GET STARTED BUTTON =====
  const getStartedBtn = document.getElementById("getStartedBtn");
  if (getStartedBtn) {
    getStartedBtn.addEventListener("click", (e) => {
      e.preventDefault();
      if (!isLoggedIn) {
        modal.style.display = "flex";
      } else {
        showPage("notes");
      }
    });
  }

  // ===== SEARCH FUNCTIONALITY =====
  const searchInput = document.getElementById("searchInput");
  if (searchInput) {
    searchInput.addEventListener("input", () => {
      const query = searchInput.value.trim().toLowerCase();

      // Filter home page skill cards
      document.querySelectorAll(".skill-card").forEach(card => {
        const subject = card.querySelector("h3").textContent.toLowerCase();
        card.style.display = subject.includes(query) ? "block" : "none";
      });

      // Filter notes library items (both static and dynamic)
      document.querySelectorAll(".notes-subject-block").forEach(block => {
        const subjectName = block.querySelector("h3").textContent.toLowerCase();
        let anyVisible = false;

        block.querySelectorAll(".notes-list li").forEach(li => {
          const text = li.querySelector("span").textContent.toLowerCase();
          const match = query === "" || text.includes(query) || subjectName.includes(query);
          li.style.display = match ? "flex" : "none";
          if (match) anyVisible = true;
        });

        block.style.display = anyVisible ? "block" : "none";
      });
    });
  }

  // ===== DOWNLOAD BUTTONS (skill cards) =====
  document.querySelectorAll(".skill-card .download-btn").forEach(btn => {
    btn.addEventListener("click", (e) => {
      e.stopPropagation();
      const subject = btn.closest(".skill-card").querySelector("h3").textContent;
      triggerDownload(`${subject} Notes`);
      showToast(`📥 ${subject} notes download started!`);
    });
  });

  // ===== DOWNLOAD BUTTONS (notes library - static items) =====
  document.querySelectorAll(".download-note-btn").forEach(btn => {
    btn.addEventListener("click", () => {
      const title = btn.closest("li").querySelector("span").textContent;
      triggerDownload(title);
      showToast(`📥 Downloading: ${title}`);
    });
  });

  // ===== QR CODE GENERATION =====
  function generateQRCode() {
    if (!attendanceActive) return;
    qrContainer.innerHTML = "";

    const code = "ATTEND-" + Math.random().toString(36).substring(2, 10).toUpperCase();
    currentQRCode = code;

    new QRCode(qrContainer, {
      text: code,
      width: 200,
      height: 200,
      colorDark: "#000000",
      colorLight: "#ffffff",
      correctLevel: QRCode.CorrectLevel.H
    });
  }

  // ===== START ATTENDANCE =====
  document.getElementById("startAttendance").addEventListener("click", () => {
    attendanceActive = true;
    generateQRCode();
    showToast("✅ Attendance started!");
  });

  // ===== STOP ATTENDANCE =====
  document.getElementById("stopAttendance").addEventListener("click", () => {
    attendanceActive = false;
    qrContainer.innerHTML = "<p style='color:gray; padding:20px;'>Attendance stopped.</p>";
    currentQRCode = null;
    showToast("🔴 Attendance stopped.");
  });

  // ===== SIMULATE QR SCAN =====
  document.getElementById("simulateScan").addEventListener("click", () => {
    const name = document.getElementById("studentName").value.trim();

    if (!attendanceActive) { showToast("⚠️ Please start attendance first."); return; }
    if (!name) { showToast("⚠️ Enter student name."); return; }
    if (!currentQRCode) { showToast("⚠️ QR not found. Restart attendance."); return; }

    if (usedCodes.has(currentQRCode)) {
      showToast("⚠️ QR already used. Wait for next one.");
      return;
    }

    usedCodes.add(currentQRCode);

    const time = new Date().toLocaleTimeString();
    attendanceList.push({ name, time });
    localStorage.setItem("attendanceList", JSON.stringify(attendanceList));

    renderAttendanceList();
    showToast(`✅ ${name} marked present at ${time}`);
    generateQRCode();
    document.getElementById("studentName").value = "";
  });

  // ===== RENDER ATTENDANCE LIST =====
  function renderAttendanceList() {
    listContainer.innerHTML = "";
    attendanceList.forEach((s, i) => {
      const li = document.createElement("li");
      li.textContent = `${i + 1}. ${s.name} — ${s.time}`;
      listContainer.appendChild(li);
    });
    studentCountEl.textContent = attendanceList.length;
  }

  renderAttendanceList();

  renderUploadedNotes();

  // ===== CLEAR ATTENDANCE =====
  document.getElementById("clearList").addEventListener("click", () => {
    if (attendanceList.length === 0) { showToast("No records to clear."); return; }
    if (confirm("Clear all attendance records?")) {
      attendanceList = [];
      localStorage.removeItem("attendanceList");
      renderAttendanceList();
      showToast("🗑 Attendance cleared.");
    }
  });

  // ===== EXPORT TO CSV =====
  document.getElementById("exportList").addEventListener("click", () => {
    if (attendanceList.length === 0) { showToast("No attendance data to export."); return; }

    let csv = "Name,Time\n";
    attendanceList.forEach(s => { csv += `${s.name},${s.time}\n`; });

    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "attendance.csv";
    a.click();
    showToast("📄 Attendance exported!");
  });

  // ===== UPLOAD FORM =====
  const uploadForm = document.getElementById("uploadForm");
  if (uploadForm) {
    uploadForm.addEventListener("submit", (e) => {
      e.preventDefault();
      const subject = document.getElementById("subject").value;
      const title = document.getElementById("uploadTitle").value.trim();
      const desc = document.getElementById("uploadDesc").value.trim();
      const fileInput = document.getElementById("fileUpload");
      const fileName = fileInput.files[0] ? fileInput.files[0].name : "";

      uploadedNotes.push({ subject, title, desc, fileName });
      localStorage.setItem("uploadedNotes", JSON.stringify(uploadedNotes));
      renderUploadedNotes();

      showToast(`✅ "${title}" uploaded for ${subject.toUpperCase()}!`);
      uploadForm.reset();
    });
  }


  // ===== ALERT CLOSE BUTTONS =====
  document.querySelectorAll(".alert-btn").forEach(btn => {
    btn.addEventListener("click", () => {
      btn.closest(".custom-alert-overlay").style.display = "none";
    });
  });

  // ===== DEMO-ONLY LINKS (footer, social, signup) =====
  document.querySelectorAll(".demo-link").forEach(el => {
    el.addEventListener("click", (e) => {
      e.preventDefault();
      showToast("🚧 This is a demo feature — not available yet!");
    });
  });

});